/**
 * Locale dictionaries for the workspace-groups browser. The namespace is
 * `workspaceGroups` (independent from ui-workspace's `workspace` namespace).
 */
import type { LocaleDictOf } from '@deepseek-ai/dsh-client-ui-slots';
/** Dictionary keys of the workspaceGroups namespace (single source of truth). */
export type WorkspaceGroupsKey = 'section.workspaces' | 'section.sessions' | 'search' | 'search.placeholder' | 'search.clear' | 'search.noMatches' | 'search.unavailable' | 'search.pending' | 'search.hasMore' | 'search.results.aria' | 'workspace.add' | 'workspace.addBusy' | 'workspace.addError' | 'workspace.addErrorTitle' | 'workspace.actionError' | 'workspace.nameDuplicate' | 'workspace.actions' | 'workspace.rename' | 'workspace.delete' | 'workspace.deleteTitle' | 'workspace.deleteConfirm' | 'workspace.deleteCancel' | 'workspace.renaming' | 'workspace.deleting' | 'workspace.renameTitle' | 'workspace.renamePlaceholder' | 'workspace.renameConfirm' | 'workspace.renameCancel' | 'workspace.moveOutOfGroup' | 'workspace.moveToGroup' | 'workspace.moveUp' | 'workspace.moveDown' | 'workspace.openFolder' | 'workspace.copyPath' | 'workspace.pathCopied' | 'directory.title' | 'directory.home' | 'directory.newFolder' | 'directory.folderName' | 'directory.create' | 'directory.cancel' | 'directory.open' | 'directory.loading' | 'directory.retry' | 'directory.showHidden' | 'directory.truncated' | 'directory.pathPlaceholder' | 'directory.go' | 'directory.refresh' | 'group.create' | 'group.createTitle' | 'group.createPlaceholder' | 'group.createConfirm' | 'group.createCancel' | 'group.creating' | 'group.renaming' | 'group.deleting' | 'group.actions' | 'group.reorder' | 'group.rename' | 'group.renameTitle' | 'group.renameConfirm' | 'group.delete' | 'group.deleteTitle' | 'group.deleteConfirm' | 'group.deleteCancel' | 'group.nameDuplicate' | 'group.nameReserved' | 'group.moveUp' | 'group.moveDown' | 'section.topLevel' | 'manual.saveError' | 'manual.conflictError' | 'session.new' | 'session.actions' | 'session.rename' | 'session.archive' | 'session.archiveError' | 'session.fork' | 'session.forkError' | 'session.renameTitle' | 'session.renamePlaceholder' | 'session.renameConfirm' | 'session.renameCancel' | 'session.renaming' | 'uncategorized' | 'empty.none' | 'empty.noWorkspaces' | 'close' | 'cancel' | 'confirm' | 'retry' | 'configUnavailable' | 'collapse' | 'expandMore' | 'newSession';
export type WorkspaceGroupsDict = LocaleDictOf<'workspaceGroups'>;
export { en } from './locales/en.js';
export { zh } from './locales/zh.js';
